services:
  db:
    image: postgres:16-alpine
    container_name: banks_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: banks_user
      POSTGRES_PASSWORD: banks_password
      POSTGRES_DB: banks
    ports:
      - "5432:5432"
    volumes:
      - banks_db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: banks_backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://banks_user:banks_password@db:5432/banks
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      PORT: 3000
      OTP_TTL_MINUTES: ${OTP_TTL_MINUTES}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_FROM: ${EMAIL_FROM}
      GROQ_API_KEY: ${GROQ_API_KEY}
    ports:
      - "3000:3000"

volumes:
  banks_db_data: